global:
  scrape_interval:     15s
  evaluation_interval: 15s
rule_files:
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'bff-marvel-api-quarkus'
    metrics_path: '/q/metrics'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8080']
  - job_name: 'bff-marvel-api-mock'
    metrics_path: '/q/metrics'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8085']