version: '3.1'
services:
  db:
    container_name: mysql
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: marveldb
    ports:
      - "3306:3306"
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.17
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"