version: '3.1'
services:
  db:
    container_name: mysql
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: marveldb
    ports:
      - "3306:3306"
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.36
    environment:
      METRICS_STORAGE_TYPE: prometheus
      PROMETHEUS_SERVER_URL: http://host.docker.internal:9090
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
  prometheus:
    container_name: prometheus
    image: "prom/prometheus"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always
  grafana:
    container_name: grafana
    image: "grafana/grafana"
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    restart: always

volumes:
  prometheus-data: